version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Calcutta
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: grunt
    versions:
    - 1.4.0
  - dependency-name: chai-html
    versions:
    - 2.0.1
  - dependency-name: chalk
    versions:
    - 4.1.1
  - dependency-name: eslintcc
    versions:
    - 0.6.0
    - 0.6.2
    - 0.6.3
    - 0.6.5
  - dependency-name: simple-git
    versions:
    - 2.32.0
    - 2.34.2
    - 2.35.0
    - 2.35.2
    - 2.36.0
    - 2.36.1
    - 2.36.2
    - 2.37.0
    - 2.38.0
  - dependency-name: date-fns
    versions:
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
    - 2.20.1
    - 2.20.2
    - 2.21.0
  - dependency-name: dependency-cruiser
    versions:
    - 9.23.0
    - 9.23.1
    - 9.23.2
    - 9.23.3
    - 9.24.0
    - 9.25.0
    - 9.25.1
  - dependency-name: md-to-pdf
    versions:
    - 3.3.2
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@gitbeaker/node"
    versions:
    - 28.1.1
    - 28.3.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: hosted-git-info
    versions:
    - 3.0.8
    - 4.0.0
    - 4.0.1
    - 4.0.2
  - dependency-name: semver
    versions:
    - 7.3.5
  - dependency-name: commander
    versions:
    - 7.1.0
    - 7.2.0
  - dependency-name: ora
    versions:
    - 5.4.0
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.6.0
    - 31.6.1
    - 32.0.0
    - 32.0.2
    - 32.2.0
    - 32.3.0
  - dependency-name: octonode
    versions:
    - 0.10.2
  - dependency-name: eslint-plugin-html
    versions:
    - 6.1.2
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: eslint-plugin-mocha
    versions:
    - 8.1.0
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: chai-datetime
    versions:
    - 1.8.0
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: ejs
    versions:
    - 3.1.6
  - dependency-name: replace-in-file
    versions:
    - 6.2.0
